/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cp_f3_java2d;

import java.awt.BasicStroke;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Stroke;
import java.awt.geom.Line2D;

/**
 *
 * @author PC
 */
public class Lineas extends javax.swing.JPanel {

    /**
     * Creates new form Lineas
     */
    public Lineas() {
        initComponents();
    }
    
    @Override
    public void paint(Graphics g) {
        
        Graphics2D g2 = (Graphics2D)g;
        
        // Dibujar borde de la cara
        Line2D l1 = new Line2D.Double(90, 90, 110, 40);       
        Line2D l2 = new Line2D.Double(110, 40, 150, 10);
        Line2D l3 = new Line2D.Double(150, 10, 200, 10);
        Line2D l4 = new Line2D.Double(200, 10, 230, 50);
        Line2D l5 = new Line2D.Double(230, 50, 240, 100);
        Line2D l6 = new Line2D.Double(240, 100, 220, 150);
        Line2D l7 = new Line2D.Double(220, 150, 240, 220);
        Line2D l8 = new Line2D.Double(240, 220, 190, 250);
        Line2D l9 = new Line2D.Double(190, 250, 150, 240);
        Line2D l10 = new Line2D.Double(150, 240, 150, 200);
        Line2D l11 = new Line2D.Double(150, 200, 100, 200);
        Line2D l12 = new Line2D.Double(100, 200, 100, 170);
        Line2D l13 = new Line2D.Double(100, 170, 110, 170);
        Line2D l14 = new Line2D.Double(110, 170, 90, 160);
        Line2D l15 = new Line2D.Double(90, 160, 110, 130);
        Line2D l16 = new Line2D.Double(97, 150, 80, 140);
        
        Line2D l17 = new Line2D.Double(80, 140, 100, 110);
        Line2D l18 = new Line2D.Double(100, 110, 90, 90);


        
        Stroke pincel = new BasicStroke(2.0f);
        g2.setStroke(pincel);
        
        g2.setColor(Color.red);
        
        // Dibujar borde de la cara
        g2.draw(l1);
        g2.draw(l2);
        g2.draw(l3);
        g2.draw(l4);
        g2.draw(l5);
        g2.draw(l6);
        g2.draw(l7);
        g2.draw(l8);
        g2.draw(l9);
        g2.draw(l10);
        g2.draw(l11);
        g2.draw(l12);
        g2.draw(l13);
        g2.draw(l14);
        g2.draw(l15);
        g2.draw(l17);
        g2.draw(l18);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 455, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 330, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
