/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cp_f3_java2d;

import java.awt.BasicStroke;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Polygon;
import java.awt.Stroke;
import java.awt.geom.Arc2D;
import java.awt.geom.Ellipse2D;
import java.awt.geom.Line2D;
import java.awt.geom.Rectangle2D;

/**
 *
 * @author PC
 */
public class Poligonos extends javax.swing.JPanel {

    /**
     * Creates new form Poligonos
     */
    public Poligonos() {
        initComponents();
    }
    
     public void paint(Graphics g) {
        
        super.paint(g);
        
        // Dibujar borde de la cara
        Line2D l1 = new Line2D.Double(150, 50, 170, 70);  
        
        // Cabeza
        Rectangle2D head = new Rectangle2D.Double(230, 170, 150, 150);
        
        // Cuerpo
        Ellipse2D body1 = new Ellipse2D.Double(255, 320, 100, 100);
        
        // Gato
        int xValues3[] = { 150, 170, 150 };
        int yValues3[] = { 20, 40, 60 }; 
        // El Ultimo valor es la cantidad de puntos
        Polygon polygon1 = new Polygon(xValues3, yValues3, 3);
        
        
        // Imagen de la izquierda triangulos 
        int tri1X[] = { 30, 110, 70 };
        int tr11Y[] = { 90, 90, 130 }; 
        Polygon tiangle1 = new Polygon(tri1X, tr11Y, 3);
        
        int tri2X[] = { 30, 50, 30 };
        int tr12Y[] = { 90, 110, 130 }; 
        Polygon tiangle2 = new Polygon(tri2X, tr12Y, 3);
        
        int tri3X[] = { 30, 70, 30 };
        int tr13Y[] = { 130, 170, 170 }; 
        Polygon tiangle3 = new Polygon(tri3X, tr13Y, 3);
        
        int tri4X[] = { 50, 90, 110, 70 };
        int tr14Y[] = { 150, 150, 170, 170 }; 
        Polygon tiangle4 = new Polygon(tri4X, tr14Y, 4);
        
                
        int tri5X[] = { 110, 110, 70 };
        int tr15Y[] = { 90, 170, 130 }; 
        Polygon tiangle5 = new Polygon(tri5X, tr15Y, 3);
        
                        
        int tri6X[] = { 70, 90, 50 };
        int tr16Y[] = { 130, 150, 150 }; 
        Polygon tiangle6 = new Polygon(tri6X, tr16Y, 3);
        
        int tri7X[] = { 50, 70, 50, 30 };
        int tr17Y[] = { 110, 130, 150, 130 }; 
        Polygon tiangle7 = new Polygon(tri7X, tr17Y, 4);
        
        
  
            
        // Stroke pincel = new BasicStroke(3.0f);
        //g.setStroke(pincel);
        
        g.setColor(Color.DARK_GRAY);
        
        // Dibujar
        g.drawPolygon(polygon1);
        g.drawPolygon(tiangle1);
        g.drawPolygon(tiangle2);
        g.drawPolygon(tiangle3);
        g.drawPolygon(tiangle4);
        g.drawPolygon(tiangle5);
        g.drawPolygon(tiangle6);
        g.drawPolygon(tiangle7);

        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
