/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cp_f3_java2d;

import java.awt.BasicStroke;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Polygon;
import java.awt.Stroke;
import java.awt.geom.Arc2D;
import java.awt.geom.Ellipse2D;
import java.awt.geom.Line2D;
import java.awt.geom.Rectangle2D;

/**
 *
 * @author PC
 */
public class Poligonos extends javax.swing.JPanel {

    /**
     * Creates new form Poligonos
     */
    public Poligonos() {
        initComponents();
    }
    
     public void paint(Graphics g) {
        
        super.paint(g);
                
        // Gato
        g.setColor(Color.YELLOW);
        int cat1X[] = { 150, 170, 150 };
        int cat1Y[] = { 20, 40, 60 }; 
        Polygon cat1 = new Polygon(cat1X, cat1Y, 3);
        g.fillPolygon(cat1);
        
        g.setColor(Color.PINK);
        int cat2X[] = { 190, 170, 190 };
        int cat2Y[] = { 20, 40, 60 }; 
        Polygon cat2 = new Polygon(cat2X, cat2Y, 3);
        g.fillPolygon(cat2);
        
        g.setColor(Color.BLUE);
        int cat3X[] = { 170, 190, 170, 150 };
        int cat3Y[] = { 40, 60, 80, 60 }; 
        Polygon cat3 = new Polygon(cat3X, cat3Y, 4);
        g.fillPolygon(cat3);
        
        g.setColor(Color.GREEN);
        int cat4X[] = { 180, 180, 150 };
        int cat4Y[] = { 70, 130, 100 }; 
        Polygon cat4 = new Polygon(cat4X, cat4Y, 3);
        g.fillPolygon(cat4);
        
        g.setColor(Color.ORANGE);
        int cat5X[] = { 180, 220, 180 };
        int cat5Y[] = { 70, 110, 150 }; 
        Polygon cat5 = new Polygon(cat5X, cat5Y, 3);
        g.fillPolygon(cat5);
        
        g.setColor(Color.MAGENTA);
        int cat6X[] = { 210, 210, 160 };
        int cat6Y[] = { 120, 170, 170 }; 
        Polygon cat6 = new Polygon(cat6X, cat6Y, 3);
        g.fillPolygon(cat6);
        
        g.setColor(Color.RED);
        int cat7X[] = { 240, 270, 240, 210 };
        int cat7Y[] = { 140, 140, 170, 170 }; 
        Polygon cat7 = new Polygon(cat7X, cat7Y, 4);
        g.fillPolygon(cat7);
        
        
      
        // Imagen de la izquierda triangulos 
        g.setColor(Color.ORANGE);
        int tri1X[] = { 30, 110, 70 };
        int tr11Y[] = { 90, 90, 130 }; 
        Polygon tiangle1 = new Polygon(tri1X, tr11Y, 3);
        g.fillPolygon(tiangle1);
        
        g.setColor(Color.PINK);
        int tri2X[] = { 30, 50, 30 };
        int tr12Y[] = { 90, 110, 130 }; 
        Polygon tiangle2 = new Polygon(tri2X, tr12Y, 3);
        g.fillPolygon(tiangle2);
        
        g.setColor(Color.GREEN);
        int tri3X[] = { 30, 70, 30 };
        int tr13Y[] = { 130, 170, 170 }; 
        Polygon tiangle3 = new Polygon(tri3X, tr13Y, 3);
        g.fillPolygon(tiangle3);
        
        g.setColor(Color.RED);
        int tri4X[] = { 50, 90, 110, 70 };
        int tr14Y[] = { 150, 150, 170, 170 }; 
        Polygon tiangle4 = new Polygon(tri4X, tr14Y, 4);
        g.fillPolygon(tiangle4);
        
        g.setColor(Color.MAGENTA);     
        int tri5X[] = { 110, 110, 70 };
        int tr15Y[] = { 90, 170, 130 }; 
        Polygon tiangle5 = new Polygon(tri5X, tr15Y, 3);
        g.fillPolygon(tiangle5);
        
        g.setColor(Color.YELLOW);           
        int tri6X[] = { 70, 90, 50 };
        int tr16Y[] = { 130, 150, 150 }; 
        Polygon tiangle6 = new Polygon(tri6X, tr16Y, 3);
        g.fillPolygon(tiangle6);
        
        g.setColor(Color.BLUE);  
        int tri7X[] = { 50, 70, 50, 30 };
        int tr17Y[] = { 110, 130, 150, 130 }; 
        Polygon tiangle7 = new Polygon(tri7X, tr17Y, 4);
        g.fillPolygon(tiangle7);
        
        
         
        g.setColor(Color.DARK_GRAY);
        
        // Dibujar
        g.drawPolygon(cat1);
        g.drawPolygon(cat2);
        g.drawPolygon(cat3);
        g.drawPolygon(cat4);
        g.drawPolygon(cat5);
        g.drawPolygon(cat6);
        g.drawPolygon(cat7);
        g.drawPolygon(tiangle1);
        g.drawPolygon(tiangle2);
        g.drawPolygon(tiangle3);
        g.drawPolygon(tiangle4);
        g.drawPolygon(tiangle5);
        g.drawPolygon(tiangle6);
        g.drawPolygon(tiangle7);

        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
